// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarColonies.Infrastructures;

#nullable disable

namespace StarColonies.Infrastructures.Migrations
{
    [DbContext(typeof(StarColoniesContext))]
    [Migration("20250428182659_GoProd")]
    partial class GoProd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ColonTeam", b =>
                {
                    b.Property<string>("MembersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("MembersId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("TeamColon", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Mac-mini-de-Maximilien1/04/2024 10:30:00Admin",
                            ConcurrencyStamp = "Mac-mini-de-Maximilien1/04/2024 10:30:00Admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Bestiaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Endurance")
                        .HasColumnType("int");

                    b.Property<int>("IdTypeBestiaire")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTypeBestiaire");

                    b.ToTable("Bestiaire");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Endurance = 2,
                            IdTypeBestiaire = 1,
                            Name = "Drone",
                            Strength = 2
                        },
                        new
                        {
                            Id = 2,
                            Endurance = 3,
                            IdTypeBestiaire = 2,
                            Name = "Anomalie",
                            Strength = 1
                        },
                        new
                        {
                            Id = 3,
                            Endurance = 12,
                            IdTypeBestiaire = 3,
                            Name = "Cryptoïde",
                            Strength = 4
                        },
                        new
                        {
                            Id = 4,
                            Endurance = 1,
                            IdTypeBestiaire = 4,
                            Name = "Spectre",
                            Strength = 7
                        },
                        new
                        {
                            Id = 5,
                            Endurance = 2,
                            IdTypeBestiaire = 1,
                            Name = "Nanobot",
                            Strength = 1
                        },
                        new
                        {
                            Id = 6,
                            Endurance = 3,
                            IdTypeBestiaire = 5,
                            Name = "Prédateur",
                            Strength = 4
                        },
                        new
                        {
                            Id = 7,
                            Endurance = 4,
                            IdTypeBestiaire = 6,
                            Name = "Chimère",
                            Strength = 4
                        },
                        new
                        {
                            Id = 8,
                            Endurance = 3,
                            IdTypeBestiaire = 3,
                            Name = "Titan",
                            Strength = 5
                        },
                        new
                        {
                            Id = 9,
                            Endurance = 11,
                            IdTypeBestiaire = 4,
                            Name = "Entité",
                            Strength = 5
                        },
                        new
                        {
                            Id = 10,
                            Endurance = 4,
                            IdTypeBestiaire = 7,
                            Name = "Mutant",
                            Strength = 2
                        },
                        new
                        {
                            Id = 11,
                            Endurance = 7,
                            IdTypeBestiaire = 3,
                            Name = "Leviathan",
                            Strength = 9
                        },
                        new
                        {
                            Id = 12,
                            Endurance = 20,
                            IdTypeBestiaire = 3,
                            Name = "Hégémon",
                            Strength = 20
                        },
                        new
                        {
                            Id = 13,
                            Endurance = 15,
                            IdTypeBestiaire = 1,
                            Name = "Drone de combat",
                            Strength = 10
                        });
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Bonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("DureeParDefaut")
                        .HasColumnType("time");

                    b.Property<int>("EffectTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Bonus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Augmente temporairement la force de tous les membres d'une équipe",
                            DureeParDefaut = new TimeSpan(0, 0, 5, 0, 0),
                            EffectTypeId = 1,
                            IconUrl = "assets/icons/potion.png",
                            Name = "Potion de force"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Investit un soldat supplémentaire pour les prochaines missions",
                            DureeParDefaut = new TimeSpan(0, 0, 3, 0, 0),
                            EffectTypeId = 3,
                            IconUrl = "assets/icons/potion.png",
                            Name = "Coup de pouce"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Augmente temporairement l'endurance de tous les membres d'une équipe",
                            DureeParDefaut = new TimeSpan(0, 0, 5, 0, 0),
                            EffectTypeId = 2,
                            IconUrl = "assets/icons/potion.png",
                            Name = "Potion d'endurance"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Double le nombre de ressources obtenues",
                            DureeParDefaut = new TimeSpan(0, 0, 1, 0, 0),
                            EffectTypeId = 4,
                            IconUrl = "assets/icons/potion.png",
                            Name = "Grâce de Midas"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Augmente l'expérience gagnée et permet de gagner un niveau supplémentaire à chaque mission",
                            DureeParDefaut = new TimeSpan(0, 0, 20, 0, 0),
                            EffectTypeId = 5,
                            IconUrl = "assets/icons/potion.png",
                            Name = "Parchemin de monsieur Swinnen"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Elimine instantanément tous les ministres",
                            DureeParDefaut = new TimeSpan(0, 1, 40, 0, 0),
                            EffectTypeId = 0,
                            IconUrl = "assets/icons/potion.png",
                            Name = "L'item trop cheatés"
                        });
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.BonusResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("BonusId", "ResourceId");

                    b.ToTable("BonusResource");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.BonusTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusId")
                        .HasColumnType("int");

                    b.Property<string>("ColonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BonusId");

                    b.HasIndex("ColonId");

                    b.ToTable("BonusTransaction");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.BonusTransactionResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusResourceId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BonusResourceId");

                    b.HasIndex("TransactionId");

                    b.ToTable("BonusTransactionResource");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Colon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateBirth")
                        .HasMaxLength(20)
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Endurance")
                        .HasColumnType("int");

                    b.Property<int>("IdProfession")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IdProfession");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ID_COLON_1",
                            AccessFailedCount = 0,
                            Avatar = "avatar_1.png",
                            ConcurrencyStamp = "03ca1f88-b451-4304-a0b6-4cbac1f31a68",
                            DateBirth = new DateTime(2005, 4, 28, 20, 26, 59, 177, DateTimeKind.Local).AddTicks(7120),
                            Email = "alex.striker@example.com",
                            EmailConfirmed = true,
                            Endurance = 2,
                            IdProfession = 1,
                            Level = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALEX.STRIKER@EXAMPLE.COM",
                            NormalizedUserName = "ALEX STRIKER",
                            PasswordHash = "AQAAAAIAAYagAAAAEEVUetnBp7FeFM6yy0sT4Uq2ss81sXrB30s0MzgXzwAar5RP4+/aWYQ54EVMa8ifkQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "faa7d029-d798-4ad7-8b15-08dff23ce8ea",
                            Strength = 5,
                            TwoFactorEnabled = false,
                            UserName = "Alex Striker"
                        },
                        new
                        {
                            Id = "ID_COLON_2",
                            AccessFailedCount = 0,
                            Avatar = "avatar_2.png",
                            ConcurrencyStamp = "b14c4d7c-cd5b-4ace-b409-280d39c9b4fb",
                            DateBirth = new DateTime(2000, 4, 28, 20, 26, 59, 210, DateTimeKind.Local).AddTicks(950),
                            Email = "mira.nova@example.com",
                            EmailConfirmed = true,
                            Endurance = 2,
                            IdProfession = 2,
                            Level = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "MIRA.NOVA@EXAMPLE.COM",
                            NormalizedUserName = "MIRA NOVA",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ8mC0iBVruo5Atlav7cE4SjNsLW4QERZVo2YdRwJsjq2NOhadx2Mht1X4zB/zyS/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d68c94e1-a614-4bce-8872-86e7480719e6",
                            Strength = 5,
                            TwoFactorEnabled = false,
                            UserName = "Mira Nova"
                        },
                        new
                        {
                            Id = "ID_COLON_3",
                            AccessFailedCount = 0,
                            Avatar = "avatar_3.png",
                            ConcurrencyStamp = "489c3fa9-a579-4809-a668-bac2cc7a9dd1",
                            DateBirth = new DateTime(1995, 4, 28, 20, 26, 59, 241, DateTimeKind.Local).AddTicks(9230),
                            Email = "elara.starfinder@example.com",
                            EmailConfirmed = true,
                            Endurance = 2,
                            IdProfession = 3,
                            Level = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "ELARA.STARFINDER@EXAMPLE.COM",
                            NormalizedUserName = "ELARA STARFINDER",
                            PasswordHash = "AQAAAAIAAYagAAAAEJndSlzy0pet9dhD2xPcnPm35q4AuuRIvIQIpY9G5sTqEsu0zrW+Bs5OEm4Biw/RNQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1e4dbb19-e83b-4d38-8197-d1eef281140f",
                            Strength = 5,
                            TwoFactorEnabled = false,
                            UserName = "Elara Starfinder"
                        },
                        new
                        {
                            Id = "ID_COLON_4",
                            AccessFailedCount = 0,
                            Avatar = "avatar_4.png",
                            ConcurrencyStamp = "a99828c7-45b0-4af6-bdee-c269bc5343f8",
                            DateBirth = new DateTime(1990, 4, 28, 20, 26, 59, 274, DateTimeKind.Local).AddTicks(2490),
                            Email = "jason.blades@example.com",
                            EmailConfirmed = true,
                            Endurance = 2,
                            IdProfession = 4,
                            Level = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "JASON.BLADES@EXAMPLE.COM",
                            NormalizedUserName = "JASON BLADES",
                            PasswordHash = "AQAAAAIAAYagAAAAECE3ba2YtIk46OpipBswVr21fWlN2wXvP2T4s5cfoMnmSsxsG8a7HbQ+3NS6A3gioQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a966e87-e0b9-44fd-931e-59b9a0916e39",
                            Strength = 5,
                            TwoFactorEnabled = false,
                            UserName = "Jason Blades"
                        },
                        new
                        {
                            Id = "ID_COLON_5",
                            AccessFailedCount = 0,
                            Avatar = "avatar_5.png",
                            ConcurrencyStamp = "23a6b1d6-473e-416b-90f0-4f485a604cea",
                            DateBirth = new DateTime(1997, 4, 28, 20, 26, 59, 306, DateTimeKind.Local).AddTicks(5210),
                            Email = "lyra.moonshadow@example.com",
                            EmailConfirmed = true,
                            Endurance = 3,
                            IdProfession = 4,
                            Level = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "LYRA.MOONSHADOW@EXAMPLE.COM",
                            NormalizedUserName = "LYRA MOONSHADOW",
                            PasswordHash = "AQAAAAIAAYagAAAAEOynJyOjXGYV0i+/UIeGc09roK//l+f8zyh/keFViDh3qP8ww/vwuyDopx5YwBN5KA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e95bd084-d6d5-4f97-addc-bf0f5d951a97",
                            Strength = 4,
                            TwoFactorEnabled = false,
                            UserName = "Lyra Moonshadow"
                        },
                        new
                        {
                            Id = "ID_COLON_6",
                            AccessFailedCount = 0,
                            Avatar = "avatar_6.png",
                            ConcurrencyStamp = "185fc2bb-4b9a-438b-aa0b-4cc237669027",
                            DateBirth = new DateTime(1993, 4, 28, 20, 26, 59, 337, DateTimeKind.Local).AddTicks(3110),
                            Email = "dax.ironfist@example.com",
                            EmailConfirmed = true,
                            Endurance = 5,
                            IdProfession = 2,
                            Level = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "DAX.IRONFIST@EXAMPLE.COM",
                            NormalizedUserName = "DAX IRONFIST",
                            PasswordHash = "AQAAAAIAAYagAAAAEGcDpKQFA9C8c+Or9q2OylSFhUU8skRPTaGxpq2BExtHxjaBApRRVULNbsneXhaqjA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96596525-997e-4d7b-8340-dc095755e7c5",
                            Strength = 6,
                            TwoFactorEnabled = false,
                            UserName = "Dax Ironfist"
                        },
                        new
                        {
                            Id = "ID_COLON_7",
                            AccessFailedCount = 0,
                            Avatar = "avatar_7.png",
                            ConcurrencyStamp = "ac81e0a4-1e87-4344-a76a-9fa6ee39ce15",
                            DateBirth = new DateTime(1999, 4, 28, 20, 26, 59, 368, DateTimeKind.Local).AddTicks(2120),
                            Email = "zara.flamewalker@example.com",
                            EmailConfirmed = true,
                            Endurance = 4,
                            IdProfession = 1,
                            Level = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZARA.FLAMEWALKER@EXAMPLE.COM",
                            NormalizedUserName = "ZARA FLAMEWALKER",
                            PasswordHash = "AQAAAAIAAYagAAAAEGmYHTt55WXfb6Xstvg2hY0MQZtLYe8JYIJJO53oVpmsWolHnG/WH+BRr/Z7vmIZpQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e6586aaf-3cb6-4739-b321-11c7075c3294",
                            Strength = 5,
                            TwoFactorEnabled = false,
                            UserName = "Zara Flamewalker"
                        },
                        new
                        {
                            Id = "ID_COLON_8",
                            AccessFailedCount = 0,
                            Avatar = "avatar_8.png",
                            ConcurrencyStamp = "c4a1adde-fe2d-40b7-b88b-e68082620eda",
                            DateBirth = new DateTime(1996, 4, 28, 20, 26, 59, 399, DateTimeKind.Local).AddTicks(5170),
                            Email = "orion.starborn@example.com",
                            EmailConfirmed = true,
                            Endurance = 3,
                            IdProfession = 3,
                            Level = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "ORION.STARBORN@EXAMPLE.COM",
                            NormalizedUserName = "ORION STARBORN",
                            PasswordHash = "AQAAAAIAAYagAAAAEC9DIZz5bqsI5jE4d7k8p5K/6+JXpb9hztJgDL/krYznGD6wmNDzB++RXM1hr4xD6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1bf6bd08-0ab5-4e2b-bdae-5fce73c092ff",
                            Strength = 5,
                            TwoFactorEnabled = false,
                            UserName = "Orion Starborn"
                        },
                        new
                        {
                            Id = "ID_COLON_9",
                            AccessFailedCount = 0,
                            Avatar = "avatar_9.png",
                            ConcurrencyStamp = "7ae78c90-2a94-4b6b-8e48-d0b578d30f9f",
                            DateBirth = new DateTime(2001, 4, 28, 20, 26, 59, 431, DateTimeKind.Local).AddTicks(5320),
                            Email = "selene.frost@example.com",
                            EmailConfirmed = true,
                            Endurance = 4,
                            IdProfession = 2,
                            Level = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "SELENE.FROST@EXAMPLE.COM",
                            NormalizedUserName = "SELENE FROST",
                            PasswordHash = "AQAAAAIAAYagAAAAEMNnUHeSdct8RlcS1ncenrbTy8/WSSyeLxJDe8ogOYMqThPfF/kA1l1GG1YzMh3T2A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f0df683f-7295-410c-908a-95ec7b13d2fd",
                            Strength = 4,
                            TwoFactorEnabled = false,
                            UserName = "Selene Frost"
                        },
                        new
                        {
                            Id = "ID_COLON_10",
                            AccessFailedCount = 0,
                            Avatar = "avatar_10.png",
                            ConcurrencyStamp = "447a4065-f665-49f3-a235-97197257fca9",
                            DateBirth = new DateTime(1998, 4, 28, 20, 26, 59, 463, DateTimeKind.Local).AddTicks(9370),
                            Email = "ryder.nightfall@example.com",
                            EmailConfirmed = true,
                            Endurance = 5,
                            IdProfession = 1,
                            Level = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "RYDER.NIGHTFALL@EXAMPLE.COM",
                            NormalizedUserName = "RYDER NIGHTFALL",
                            PasswordHash = "AQAAAAIAAYagAAAAEHjy+ycaLif5S9WbZ/OMU42k2T3ljsP7aYUmvLhK+98xAwWQhpFrwOcjMUyo8qdp+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "98a9f97a-6976-48ae-b01d-fd318e454d59",
                            Strength = 5,
                            TwoFactorEnabled = false,
                            UserName = "Ryder Nightfall"
                        });
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.ColonBonus", b =>
                {
                    b.Property<string>("ColonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BonusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAchat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("ColonId", "BonusId");

                    b.HasIndex("BonusId");

                    b.ToTable("ColonBonus");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.ColonResource", b =>
                {
                    b.Property<string>("ColonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ColonId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("ColonResource", (string)null);
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateHeureAction")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequeteAction")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ResponseAction")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Mission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Une ancienne base de recherche abandonnée recèle des créatures étranges et des technologies perdues.",
                            Image = "base_abandonnee.jpg",
                            Name = "Exploration de la base abandonnée"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Un monstre marin légendaire menace les colonies côtières. Son élimination est primordiale.",
                            Image = "leviathan_abysses.jpg",
                            Name = "Chasse au Léviathan des abysses"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Des scientifiques sont piégés dans une zone contaminée par des créatures expérimentales.",
                            Image = "quarantaine_zone.jpg",
                            Name = "Sauvetage dans la zone de quarantaine"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Une entité extraterrestre intelligente a pris le contrôle d'un réacteur nucléaire.",
                            Image = "hegemon_reactor.jpg",
                            Name = "Désactivation du Hégémon"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Des créatures extraterrestres ont infesté d'anciennes ruines découvertes sur une lune lointaine.",
                            Image = "ruines_aliennes.jpg",
                            Name = "Nettoyage des ruines aliennes"
                        });
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.MissionBestiaire", b =>
                {
                    b.Property<int>("IdMission")
                        .HasColumnType("int");

                    b.Property<int>("IdBestiaire")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("IdMission", "IdBestiaire");

                    b.HasIndex("IdBestiaire");

                    b.ToTable("MissionBestiaire");

                    b.HasData(
                        new
                        {
                            IdMission = 1,
                            IdBestiaire = 1,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 1,
                            IdBestiaire = 2,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 1,
                            IdBestiaire = 3,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 1,
                            IdBestiaire = 4,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 2,
                            IdBestiaire = 5,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 2,
                            IdBestiaire = 6,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 2,
                            IdBestiaire = 7,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 2,
                            IdBestiaire = 8,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 3,
                            IdBestiaire = 9,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 3,
                            IdBestiaire = 10,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 3,
                            IdBestiaire = 11,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 3,
                            IdBestiaire = 12,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 4,
                            IdBestiaire = 13,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 4,
                            IdBestiaire = 1,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 4,
                            IdBestiaire = 2,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 4,
                            IdBestiaire = 3,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 4,
                            IdBestiaire = 4,
                            Id = 0
                        },
                        new
                        {
                            IdMission = 4,
                            IdBestiaire = 5,
                            Id = 0
                        });
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.MissionResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdMission")
                        .HasColumnType("int");

                    b.Property<int>("IdResource")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMission");

                    b.HasIndex("IdResource");

                    b.ToTable("MissionResource");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdMission = 1,
                            IdResource = 1
                        },
                        new
                        {
                            Id = 2,
                            IdMission = 1,
                            IdResource = 2
                        },
                        new
                        {
                            Id = 3,
                            IdMission = 2,
                            IdResource = 3
                        },
                        new
                        {
                            Id = 4,
                            IdMission = 2,
                            IdResource = 4
                        },
                        new
                        {
                            Id = 5,
                            IdMission = 3,
                            IdResource = 5
                        },
                        new
                        {
                            Id = 6,
                            IdMission = 3,
                            IdResource = 6
                        },
                        new
                        {
                            Id = 7,
                            IdMission = 4,
                            IdResource = 7
                        },
                        new
                        {
                            Id = 8,
                            IdMission = 4,
                            IdResource = 8
                        },
                        new
                        {
                            Id = 9,
                            IdMission = 5,
                            IdResource = 9
                        },
                        new
                        {
                            Id = 10,
                            IdMission = 5,
                            IdResource = 10
                        });
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Profession");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Un ingénieur est une personne qui conçoit et construit des machines.",
                            Icone = "avatars/engineer.png",
                            Name = "Ingénieur"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Un médecin est une personne qui soigne les maladies.",
                            Icone = "avatars/doctor.png",
                            Name = "Médecin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Un scientifique est une personne qui étudie la science.",
                            Icone = "avatars/scientist.png",
                            Name = "Scientifique"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Un soldat est une personne qui combat pour son pays.",
                            Icone = "avatars/soldier.png",
                            Name = "Soldat"
                        });
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdTypeResource")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdTypeResource");

                    b.ToTable("Resource");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Matériau de protection léger",
                            IdTypeResource = 1,
                            Name = "Elindage léger"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Technologie de stockage d'énergie",
                            IdTypeResource = 2,
                            Name = "Batterie compacte"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Composant technologique avancé",
                            IdTypeResource = 2,
                            Name = "Module quantique"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Matériau haute résistance",
                            IdTypeResource = 1,
                            Name = "Nanofibres"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Matériau de protection renforcé",
                            IdTypeResource = 1,
                            Name = "Elindage renforcé"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Arme technologique",
                            IdTypeResource = 2,
                            Name = "Mitraillette"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Artefact mystérieux",
                            IdTypeResource = 3,
                            Name = "Gros crâne d'Alex"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Matériau suspect",
                            IdTypeResource = 1,
                            Name = "Residus louches"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Substance consommable dégradée",
                            IdTypeResource = 5,
                            Name = "Vinade avariée"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Matériau provenant de dents animales",
                            IdTypeResource = 1,
                            Name = "Crocs tranchants"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Substance consommable bioluminescente",
                            IdTypeResource = 5,
                            Name = "Sang fluorescent"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Connaissance génétique",
                            IdTypeResource = 4,
                            Name = "ADN cryptoïen"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Artefact de protection massive",
                            IdTypeResource = 3,
                            Name = "Enorme casque"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Boisson consommable",
                            IdTypeResource = 5,
                            Name = "Petite bière"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Matériau de protection naturelle",
                            IdTypeResource = 1,
                            Name = "Ecaille solide"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Substance consommable dangereuse",
                            IdTypeResource = 5,
                            Name = "Venin mortel"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Artefact énigmatique",
                            IdTypeResource = 3,
                            Name = "Cœur de l'Hégémon"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Connaissance stratégique",
                            IdTypeResource = 4,
                            Name = "Plan d'attaque"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Matériau spectral",
                            IdTypeResource = 1,
                            Name = "Membrane fantomique"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Connaissance extrasensorielle",
                            IdTypeResource = 4,
                            Name = "Clairevoyance"
                        });
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.ResultatMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMission")
                        .HasColumnType("int");

                    b.Property<int>("IdTeam")
                        .HasColumnType("int");

                    b.Property<double>("IssueEndurance")
                        .HasColumnType("float");

                    b.Property<double>("IssueStrength")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdMission");

                    b.HasIndex("IdTeam");

                    b.ToTable("ResultatMission");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baniere")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdColonCreator")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdColonCreator");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.TypeBestiaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeBestiaire");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "Avatar1.png",
                            Description = "Créations mécaniques ou cybernétiques, souvent conçues pour des tâches spécifiques. Peuvent aller des assistants domestiques aux machines de guerre autonomes.",
                            Name = "Robot"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "icons/naturelle.png",
                            Description = "Êtres organiques issus de l'évolution naturelle, parfaitement adaptés à leur écosystème. Inclut les créatures des forêts, des océans et autres habitats terrestres.",
                            Name = "Naturelle"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "icons/extraterrestre.png",
                            Description = "Formes de vie originaires d'autres planètes ou dimensions, possédant souvent des caractéristiques biologiques exotiques et des capacités inexplicables.",
                            Name = "Extraterrestre"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "icons/paranormal.png",
                            Description = "Entités défiant les lois de la physique, souvent liées à des phénomènes spirituels ou énigmatiques. Inclut fantômes, esprits et créatures dimensionnelles.",
                            Name = "Paranormal"
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "icons/animal.png",
                            Description = "Espèces animales terrestres, qu'elles soient communes ou rares. Peuvent inclure des variants évolués ou génétiquement modifiés.",
                            Name = "Animal"
                        },
                        new
                        {
                            Id = 6,
                            Avatar = "icons/experience.png",
                            Description = "Résultats d'expérimentations scientifiques ou magiques, combinant souvent des traits de multiples espèces. Créatures instables aux capacités imprévisibles.",
                            Name = "Expérience"
                        },
                        new
                        {
                            Id = 7,
                            Avatar = "icons/humanoide.png",
                            Description = "Êtres bipèdes à morphologie semblable aux humains, qu'ils soient d'origine naturelle ou artificielle. Peuvent posséder une intelligence avancée et une société structurée.",
                            Name = "Humanoïde"
                        });
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.TypeResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeResource");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Matériau de construction",
                            Icon = "icons/materiau.png",
                            Name = "Matériau"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Technologie avancée",
                            Icon = "icons/technologie.png",
                            Name = "Technologie"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Artefact ancien",
                            Icon = "icons/artefact.png",
                            Name = "Artefact"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Connaissance avancée",
                            Icon = "icons/connaissance.png",
                            Name = "Connaissance"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Consomable de base",
                            Icon = "icons/consomable.png",
                            Name = "Consomable"
                        });
                });

            modelBuilder.Entity("ColonTeam", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Colon", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarColonies.Infrastructures.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Colon", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Colon", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarColonies.Infrastructures.Entities.Colon", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Colon", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Bestiaire", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.TypeBestiaire", "TypeBestiaire")
                        .WithMany("Bestiaire")
                        .HasForeignKey("IdTypeBestiaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypeBestiaire");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.BonusResource", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Bonus", "Bonus")
                        .WithMany("BonusResources")
                        .HasForeignKey("BonusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarColonies.Infrastructures.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bonus");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.BonusTransaction", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Bonus", "Bonus")
                        .WithMany()
                        .HasForeignKey("BonusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarColonies.Infrastructures.Entities.Colon", "Colon")
                        .WithMany()
                        .HasForeignKey("ColonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bonus");

                    b.Navigation("Colon");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.BonusTransactionResource", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.BonusResource", "BonusResource")
                        .WithMany()
                        .HasForeignKey("BonusResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarColonies.Infrastructures.Entities.BonusTransaction", "Transaction")
                        .WithMany("TransactionResources")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusResource");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Colon", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("IdProfession")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.ColonBonus", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Bonus", "Bonus")
                        .WithMany("ColonBonuses")
                        .HasForeignKey("BonusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarColonies.Infrastructures.Entities.Colon", "Colon")
                        .WithMany("ColonBonuses")
                        .HasForeignKey("ColonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bonus");

                    b.Navigation("Colon");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.ColonResource", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Colon", "Colon")
                        .WithMany("ColonResources")
                        .HasForeignKey("ColonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarColonies.Infrastructures.Entities.Resource", "Resource")
                        .WithMany("ColonResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colon");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.MissionBestiaire", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Bestiaire", "Bestiaire")
                        .WithMany("MissionBestiaires")
                        .HasForeignKey("IdBestiaire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarColonies.Infrastructures.Entities.Mission", "Mission")
                        .WithMany("MissionBestiaires")
                        .HasForeignKey("IdMission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bestiaire");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.MissionResource", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Mission", "Mission")
                        .WithMany("GainedResources")
                        .HasForeignKey("IdMission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarColonies.Infrastructures.Entities.Resource", "Resource")
                        .WithMany("MissionResources")
                        .HasForeignKey("IdResource")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Resource", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.TypeResource", "TypeResource")
                        .WithMany("Resources")
                        .HasForeignKey("IdTypeResource")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeResource");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.ResultatMission", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Mission", "Mission")
                        .WithMany("ResultatMissions")
                        .HasForeignKey("IdMission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarColonies.Infrastructures.Entities.Team", "Team")
                        .WithMany("ResultatMissions")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Team", b =>
                {
                    b.HasOne("StarColonies.Infrastructures.Entities.Colon", "ColonCreator")
                        .WithMany()
                        .HasForeignKey("IdColonCreator")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ColonCreator");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Bestiaire", b =>
                {
                    b.Navigation("MissionBestiaires");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Bonus", b =>
                {
                    b.Navigation("BonusResources");

                    b.Navigation("ColonBonuses");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.BonusTransaction", b =>
                {
                    b.Navigation("TransactionResources");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Colon", b =>
                {
                    b.Navigation("ColonBonuses");

                    b.Navigation("ColonResources");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Mission", b =>
                {
                    b.Navigation("GainedResources");

                    b.Navigation("MissionBestiaires");

                    b.Navigation("ResultatMissions");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Resource", b =>
                {
                    b.Navigation("ColonResources");

                    b.Navigation("MissionResources");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.Team", b =>
                {
                    b.Navigation("ResultatMissions");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.TypeBestiaire", b =>
                {
                    b.Navigation("Bestiaire");
                });

            modelBuilder.Entity("StarColonies.Infrastructures.Entities.TypeResource", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
